dependencies {
    api project(':dependencies:redis-auto-configuration')
    api project(':dependencies:mongo-auto-configuration')
    api project(':dependencies:web-configuration')

    testImplementation(project(path: ':dependencies:mongo-auto-configuration', configuration: 'tests'))
    testImplementation project(path: ':dependencies:web-configuration', configuration: 'tests')
    testImplementation project(path: ':dependencies:redis-auto-configuration', configuration: 'tests')
}

task jarTests(type: Jar, dependsOn: testClasses) {
    archiveClassifier = 'tests'
    from sourceSets.test.output
}

configurations {
    tests {
        extendsFrom testImplementation
    }
}
artifacts {
    tests jarTests
}

