version: 2.1

orbs:
    aws-cli: circleci/aws-cli@2.0.3
    aws-ecr: circleci/aws-ecr@7.0.0
    kubernetes: circleci/kubernetes@0.12.0
    envsubst: sawadashota/envsubst@1.1.0
    helm: circleci/helm@1.2.0

# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
executors:
    java-executor: # linux executor using the node base image
        docker:
            -   image: cimg/openjdk:14.0.2

jobs:
    checkout:
        executor: java-executor
        steps:
            - checkout
            -   restore_cache:
                    keys:
                        - gradle-{{ .Branch }}-{{ checksum "build.gradle" }}
                        - gradle-{{ .Branch }}-
                        - gradle-
            -   save_cache:
                    key: gradle-{{ .Branch }}-{{ checksum "build.gradle" }}
                    paths:
                        - ~/.gradle/caches
                        - ~/.gradle/wrapper
                        - ~/project/bin/main
                        - ~/project/bin/test
            -   persist_to_workspace:
                    root: .
                    paths:
                        - ./*
    test:
        executor: java-executor
        parameters:
            service-name:
                type: string

        steps:
            -   attach_workspace:
                    at: .
            -   run: ./gradlew  :services:<<parameters.service-name>>:test
    buildDocker:
        executor: java-executor
        parameters:
            service-name:
                type: string
        steps:
            -   attach_workspace:
                    at: .
            -   setup_remote_docker:
                    docker_layer_caching: false
            -   run:
                    name: Build docker image
                    command: ./gradlew  -DDOCKER_REGISTRY=${AWS_ECR_ACCOUNT_URL}  :services:<<parameters.service-name>>:buildDocker -x test -Dservice-name=segmentme-<<parameters.service-name>>
            -   run: docker images
            -   run:
                    name: Save image to an archive
                    command: |
                        mkdir docker-image
                        docker save -o docker-image/image.tar ${AWS_ECR_ACCOUNT_URL}/segmentme-<<parameters.service-name>>:latest
            -   persist_to_workspace:
                    root: .
                    paths:
                        - docker-image
    publish:
        executor: java-executor
        parameters:
            service-name:
                type: string
        environment:
            AWS_DEFAULT_OUTPUT: json
        steps:
            - setup_remote_docker
            -   attach_workspace:
                    at: workspace
            -   run:
                    name: Load image
                    command: |
                        docker load --input workspace/docker-image/image.tar
            - aws-ecr/ecr-login
            -   run: docker images
            -   aws-ecr/push-image:
                    repo: segmentme-<<parameters.service-name>>
    deploy:
        executor: java-executor
        parameters:
            service-name:
                type: string
            cluster-name:
                type: string
        environment:
            AWS_DEFAULT_OUTPUT: json
        steps:
            -   attach_workspace:
                    at: .
            - kubernetes/install-kubectl
            - helm/install-helm-client
            - aws-cli/install
            - envsubst/install
            -   run:
                    name: Setup EKS
                    command: |
                        aws eks update-kubeconfig --name <<parameters.cluster-name>>
            -   run:
                    name: Deploy
                    command: |
                        cd ./kubernetes/infrastructure
                        . ./environment.sh
                        printenv
                        cd ../../helm
                        envsubst < ./common/values.yaml > ./values.yaml
                        grep ""  ./values.yaml
                        helm dependency build ./<<parameters.service-name>>
                        helm upgrade --install <<parameters.service-name>> -f values.yaml ./<<parameters.service-name>>
    apply-kube-infrastructure:
        executor: java-executor
        environment:
            AWS_DEFAULT_OUTPUT: json
        parameters:
            cluster-name:
                type: string
        steps:
            -   attach_workspace:
                    at: .
            - kubernetes/install-kubectl
            - aws-cli/install
            - envsubst/install
            -   run:
                    name: Setup EKS
                    command: |
                        aws eks update-kubeconfig --name <<parameters.cluster-name>>
            -   run:
                    name: Prepare custom environment variables
                    command: |
                        cd ./kubernetes/infrastructure
                        . ./environment.sh
            -   run:
                    name: Create secret
                    command: |
                        cd ./kubernetes/infrastructure
                        ./kube-create-auth0-secrets.sh
            -   run:
                    name: Create target groups
                    command: |
                        cd ./kubernetes/infrastructure
                        ./deploy_tgs.sh



# the default pipeline parameters, which will be updated according to
# the results of the path-filtering orb
parameters:
    access-control-service-changed:
        type: boolean
        default: false
    measurement-service-changed:
        type: boolean
        default: false
    management-service-changed:
        type: boolean
        default: false
    analysis-service-changed:
        type: boolean
        default: false
    analysis-api-service-changed:
        type: boolean
        default: false
    channel-service-changed:
        type: boolean
        default: false
    core-changed:
        type: boolean
        default: false
    kube-infra-changed:
        type: boolean
        default: false
    common-chart-changed:
        type: boolean
        default: false
    access-control-service-chart-changed:
        type: boolean
        default: false
    measurement-service-chart-changed:
        type: boolean
        default: false
    management-service-chart-changed:
        type: boolean
        default: false
    analysis-service-chart-changed:
        type: boolean
        default: false
    analysis-api-service-chart-changed:
        type: boolean
        default: false
    channel-service-chart-changed:
        type: boolean
        default: false
# here we specify our workflows, most of which are conditionally
# executed based upon pipeline parameter values. Each workflow calls a
# specific job defined above, in the jobs section.
workflows:
    kube-infrastructure:
            when: << pipeline.parameters.kube-infra-changed >>
            jobs:
                - checkout
                -   apply-kube-infrastructure:
                        context:
                            - sme
                        cluster-name: segmentme-demo-eks
                        requires:
                            - checkout

        access-control-service:
            when:
                or:
                    - << pipeline.parameters.core-changed >>
                    - << pipeline.parameters.access-control-service-changed >>
                    - << pipeline.parameters.common-chart-changed >>
                    - << pipeline.parameters.access-control-service-chart-changed >>
            jobs:
                - checkout
                -   test:
                        context:
                            - sme
                        service-name: access-control-service
                        requires:
                            - checkout
                -   buildDocker:
                        context:
                            - sme
                        service-name: access-control-service
                        requires:
                            - test
                -   publish_gate:
                        type: approval
                        requires:
                            - buildDocker
                -   publish:
                        context:
                            - sme
                        service-name: access-control-service
                        requires:
                            - publish_gate
                -   deploy:
                        context:
                            - sme
                        service-name: access-control-service
                        cluster-name: segmentme-demo-eks
                        requires:
                            - publish
    #    measurement-service:
    #        when:
    #            or:
    #                - << pipeline.parameters.core-changed >>
    #                - << pipeline.parameters.measurement-service-changed >>
    #                - << pipeline.parameters.common-chart-changed >>
    #                - << pipeline.parameters.measurement-service-chart-changed >>
    #        jobs:
    #            - checkout
    #            -   test:
    #                    context:
    #                        - sme
    #                    service-name: measurement-service
    #                    requires:
    #                        - checkout
    #            -   buildDocker:
    #                    context:
    #                        - sme
    #                    service-name: measurement-service
    #                    requires:
    #                        - test
    #            -   publish_gate:
    #                    type: approval
    #                    requires:
    #                        - buildDocker
    #            -   publish:
    #                    context:
    #                        - sme
    #                    service-name: measurement-service
    #                    requires:
    #                        - publish_gate
    #            -   deploy:
    #                    context:
    #                        - sme
    #                    service-name: measurement-service
    #                    cluster-name: segmentme-demo-eks
    #                    requires:
    #                        - publish
    #    management-service:
    #        when:
    #            or:
    #                - << pipeline.parameters.core-changed >>
    #                - << pipeline.parameters.management-service-changed >>
    #                - << pipeline.parameters.common-chart-changed >>
    #                - << pipeline.parameters.management-service-chart-changed >>
    #        jobs:
    #            - checkout
    #            -   test:
    #                    context:
    #                        - sme
    #                    service-name: management-service
    #                    requires:
    #                        - checkout
    #            -   buildDocker:
    #                    context:
    #                        - sme
    #                    service-name: management-service
    #                    requires:
    #                        - test
    #            -   publish_gate:
    #                    type: approval
    #                    requires:
    #                        - buildDocker
    #            -   publish:
    #                    context:
    #                        - sme
    #                    service-name: management-service
    #                    requires:
    #                        - publish_gate
    #            -   deploy:
    #                    context:
    #                        - sme
    #                    service-name: management-service
    #                    cluster-name: segmentme-demo-eks
    #                    requires:
    #                        - publish
    analysis-service:
        when:
            or:
                - << pipeline.parameters.core-changed >>
                - << pipeline.parameters.analysis-service-changed >>
                - << pipeline.parameters.common-chart-changed >>
                - << pipeline.parameters.analysis-service-chart-changed >>
        jobs:
            - checkout
            -   test:
                    context:
                        - sme
                    service-name: analysis-service
                    requires:
                        - checkout
            -   buildDocker:
                    context:
                        - sme
                    service-name: analysis-service
                    requires:
                        - test
            -   publish_gate:
                    type: approval
                    requires:
                        - buildDocker
            -   publish:
                    context:
                        - sme
                    service-name: analysis-service
                    requires:
                        - publish_gate
            -   deploy:
                    context:
                        - sme
                    service-name: analysis-service
                    cluster-name: segmentme-demo-eks
                    requires:
                        - publish
#    analysis-api-service:
#        when:
#            or:
#                - << pipeline.parameters.core-changed >>
#                - << pipeline.parameters.analysis-api-service-changed >>
#                - << pipeline.parameters.common-chart-changed >>
#                - << pipeline.parameters.analysis-api-service-chart-changed>>
#        jobs:
#            - checkout
#            -   test:
#                    context:
#                        - sme
#                    service-name: analysis-api-service
#                    requires:
#                        - checkout
#            -   buildDocker:
#                    context:
#                        - sme
#                    service-name: analysis-api-service
#                    requires:
#                        - test
#            -   publish_gate:
#                    type: approval
#                    requires:
#                        - buildDocker
#            -   publish:
#                    context:
#                        - sme
#                    service-name: analysis-api-service
#                    requires:
#                        - publish_gate
#            -   deploy:
#                    context:
#                        - sme
#                    service-name: analysis-api-service
#                    cluster-name: segmentme-demo-eks
#                    requires:
#                        - publish
#    channel-service:
#        when:
#            or:
#                - << pipeline.parameters.core-changed >>
#                - << pipeline.parameters.channel-service-changed >>
#                - << pipeline.parameters.common-chart-changed >>
#                - << pipeline.parameters.channel-service-chart-changed>>
#        jobs:
#            - checkout
#            -   test:
#                    context:
#                        - sme
#                    service-name: channel-service
#                    requires:
#                        - checkout
#            -   buildDocker:
#                    context:
#                        - sme
#                    service-name: channel-service
#                    requires:
#                        - test
#            -   publish_gate:
#                    type: approval
#                    requires:
#                        - buildDocker
#            -   publish:
#                    context:
#                        - sme
#                    service-name: channel-service
#                    requires:
#                        - publish_gate
#            -   deploy:
#                    context:
#                        - sme
#                    service-name: channel-service
#                    cluster-name: segmentme-demo-eks
#                    requires:
#                        - publish