version: 2.1


# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#

jobs:
    build:
        docker:
            # specify the version you desire here
            -   image: cimg/openjdk:14.0.2

            # Specify service dependencies here if necessary
            # CircleCI maintains a library of pre-built images
            # documented at https://circleci.com/docs/2.0/circleci-images/
            # - image: circleci/postgres:9.4

        working_directory: ~/repo

        environment:
            # Customize the JVM maximum heap limit
            JVM_OPTS: -Xmx3200m
            TERM: dumb

    test:
        parameters:
            service-name:
                type: string
        steps:
            -   run: ./gradlew  :services:<<parameters.service-name>>:test

# the default pipeline parameters, which will be updated according to
# the results of the path-filtering orb
parameters:
    access-control-service-changed:
        type: boolean
        default: false
    measurement-service-changed:
        type: boolean
        default: false
    management-service-changed:
        type: boolean
        default: false
    analysis-service-changed:
        type: boolean
        default: false
    analysis-api-service-changed:
        type: boolean
        default: false
    channel-service-changed:
        type: boolean
        default: false

# here we specify our workflows, most of which are conditionally
# executed based upon pipeline parameter values. Each workflow calls a
# specific job defined above, in the jobs section.
workflows:
    # when pipeline parameter, access-control-service-changed is true, the
    # build-service-1 job is triggered.
    access-control-service:
        when: << pipeline.parameters.access-control-service-changed >>
        jobs:
            - build
            -   test:
                    matrix:
                        parameters:
                            service-name: [ access-control-service ]
#    measurement-service:
#        when: << pipeline.parameters.measurement-service-changed >>
#        jobs:
#            - ./gradlew  :services:measurement-service:test
#    management-service:
#        when: << pipeline.parameters.management-service-changed >>
#        jobs:
#            - ./gradlew  :services:management-service:test
#    # when pipeline parameter, measurement-service-changed is true, the
#    analysis-service:
#        when: << pipeline.parameters.analysis-service-changed >>
#        jobs:
#            - ./gradlew  :services:analysis-service:test
#    analysis-api-service:
#        when: << pipeline.parameters.analysis-api-service-changed >>
#        jobs:
#            - ./gradlew  :services:analysis-api-service:test
#    channel-service:
#        when: << pipeline.parameters.channel-service-changed >>
#        jobs:
#            - ./gradlew  :services:channel-service:test

#    # when pipeline parameter, access-control-service-changed OR
#    # measurement-service-changed is true, run-integration-tests job is
#    # triggered. see:
#    # https://circleci.com/docs/2.0/configuration-reference/#logic-statements
#    # for more information.
#    run-integration-tests:
#        when:
#            or: [<< pipeline.parameters.access-control-service-changed >>, << pipeline.parameters.measurement-service-changed >>]
#        jobs:
#            - maven/test:
#                  name: run-integration-tests
#                  command: '-X verify'
#                  app_src_directory: 'tests'