version: 2.1


# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
executors:
    java-executor: # linux executor using the node base image
        docker:
            -   image: cimg/openjdk:14.0.2

jobs:
    checkout:
        executor: java-executor
        working_directory: ~/repo
        steps:
            - checkout
    test:
        executor: java-executor
        parameters:
            service-name:
                type: string
        steps:
            -   run: ls
            -   run: pwd
            -   run: ./gradlew  :services:<<parameters.service-name>>:test
    buildDocker:
        executor: java-executor
        working_directory: ~/repo
        environment:
            SME_BE_HOST: http://192.168.1.14
        parameters:
            service-name:
                type: string
        steps:
            -   run: ls
            -   run: pwd
            -   run: ./gradlew  -DSME_BE_HOST=${SME_BE_HOS} -DDOCKER_REGISTRY=${AWS_ECR_ACCOUNT_URL}  :services:<<parameters.service-name>>:buildDocker -x test -Dservice-name=segmentme-<<parameters.service-name>>

# the default pipeline parameters, which will be updated according to
# the results of the path-filtering orb
parameters:
    access-control-service-changed:
        type: boolean
        default: false
    measurement-service-changed:
        type: boolean
        default: false
    management-service-changed:
        type: boolean
        default: false
    analysis-service-changed:
        type: boolean
        default: false
    analysis-api-service-changed:
        type: boolean
        default: false
    channel-service-changed:
        type: boolean
        default: false

# here we specify our workflows, most of which are conditionally
# executed based upon pipeline parameter values. Each workflow calls a
# specific job defined above, in the jobs section.
workflows:
    always-run:
        jobs:
            - checkout
    # when pipeline parameter, access-control-service-changed is true, the
    # build-service-1 job is triggered.
    access-control-service:
        when: << pipeline.parameters.access-control-service-changed >>
        jobs:
            -   test:
                    name: test
                    matrix:
                        parameters:
                            service-name: [ access-control-service ]
            -   buildDocker:
                    name: build
                    requires:
                        - test
                    matrix:
                        parameters:
                            service-name: [ access-control-service ]
#    measurement-service:
#        when: << pipeline.parameters.measurement-service-changed >>
#        jobs:
#            - ./gradlew  :services:measurement-service:test
#    management-service:
#        when: << pipeline.parameters.management-service-changed >>
#        jobs:
#            - ./gradlew  :services:management-service:test
#    # when pipeline parameter, measurement-service-changed is true, the
#    analysis-service:
#        when: << pipeline.parameters.analysis-service-changed >>
#        jobs:
#            - ./gradlew  :services:analysis-service:test
#    analysis-api-service:
#        when: << pipeline.parameters.analysis-api-service-changed >>
#        jobs:
#            - ./gradlew  :services:analysis-api-service:test
#    channel-service:
#        when: << pipeline.parameters.channel-service-changed >>
#        jobs:
#            - ./gradlew  :services:channel-service:test

#    # when pipeline parameter, access-control-service-changed OR
#    # measurement-service-changed is true, run-integration-tests job is
#    # triggered. see:
#    # https://circleci.com/docs/2.0/configuration-reference/#logic-statements
#    # for more information.
#    run-integration-tests:
#        when:
#            or: [<< pipeline.parameters.access-control-service-changed >>, << pipeline.parameters.measurement-service-changed >>]
#        jobs:
#            - maven/test:
#                  name: run-integration-tests
#                  command: '-X verify'
#                  app_src_directory: 'tests'