logging:
    level:
        root: INFO
auth0:
  audience: https://dev-j1y3rcr7oreu5sq8.us.auth0.com/api/v2/
  managementApi: https://dev-j1y3rcr7oreu5sq8.us.auth0.com/api/v2/
spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ${AUTH0_CLIENT_ID:zNUSPZ4zKcyZVMFybWmZt72iaE4RWZfO}
            client-secret: ${AUTH0_CLIENT_SECRET:BDLzgc39FTIAWNdydtcIOE0qSEZK54F6wXfkRmCmMSsOd5y90LNok6-HcD5L6DYL}
            authorization-grant-type: client_credentials
            clientAuthenticationMethod: post
        provider:
          auth0:
            token-uri: https://dev-j1y3rcr7oreu5sq8.us.auth0.com/oauth/token
      resourceserver:
        jwt:
          issuer-uri: https://dev-j1y3rcr7oreu5sq8.us.auth0.com/
segmentme:
  application:
    security:
      ignored:
        endpoints: [ /analysis/connect, /analysis/analyze/** ]
        sdkEndpoints: [ /analysis/connect, /analysis/analyze/** ]
    web-client:
      configuration:
        analysis-service-client:
          connection:
            connectTimeOut: 20000  #milisecond
            readTimeOut: 10000  #milisecond
            writeTimeOut: 10000 #milisecond
          host: ${ANALYSIS_SERVICE_HOST:http://localhost:8082}
        access-control-service:
          connection:
            connectTimeOut: 20000  #milisecond
            readTimeOut: 10000  #milisecond
            writeTimeOut: 10000 #milisecond
          host: ${ACCESS_SERVICE_HOST:http://localhost:8085}
        management-service-client:
          connection:
            connectTimeOut: 20000  #milisecond
            readTimeOut: 10000  #milisecond
            writeTimeOut: 10000 #milisecond
          host: ${MANAGEMENT_SERVICE_HOST:http://localhost:8084}
server:
  port: 8086
