//todo vk : rethink usage of common DTO's modules due to it lead to service coupling.
dependencies {
    implementation group: 'com.fasterxml.jackson.core', name: 'jackson-annotations', version: '2.12.1'
    api project(':dependencies:models:shared')
    api group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.11.2'
    implementation group: 'javax.validation', name: 'validation-api', version: '2.0.1.Final'

}
