dependencies {
    api project(':dependencies:redis-auto-configuration')
    api project(':dependencies:web-configuration')
    api project(':dependencies:helpers:context-processor')
    api project(':dependencies:mongo-auto-configuration')
    api project(':dependencies:models:dto:analysis-dto')
    testImplementation project(path: ':dependencies:mongo-auto-configuration', configuration: 'tests')
    testImplementation project(path: ':dependencies:helpers:context-processor', configuration: 'tests')
}
