dependencies {
    api project(':dependencies:web-configuration')
    api project(':dependencies:models:dto:analysis-dto')
    implementation group: 'javax.validation', name: 'validation-api', version: '2.0.1.Final'

    testImplementation project(path: ':services:management-service', configuration: 'tests')
    testImplementation 'org.springframework.security:spring-security-test'
}