logging:
  level:
      root: INFO
auth0:
  audience: https://dev-j1y3rcr7oreu5sq8.us.auth0.com/api/v2/
  managementApi: https://dev-j1y3rcr7oreu5sq8.us.auth0.com/api/v2/
spring:
  data:
    mongodb:
      auto-index-creation: on
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: ${AUTH0_CLIENT_ID:zNUSPZ4zKcyZVMFybWmZt72iaE4RWZfO}
            client-secret: ${AUTH0_CLIENT_SECRET:BDLzgc39FTIAWNdydtcIOE0qSEZK54F6wXfkRmCmMSsOd5y90LNok6-HcD5L6DYL}
            authorization-grant-type: client_credentials
            clientAuthenticationMethod: post
        provider:
          auth0:
            token-uri: https://dev-j1y3rcr7oreu5sq8.us.auth0.com/oauth/token
      resourceserver:
        jwt:
          issuer-uri: https://dev-j1y3rcr7oreu5sq8.us.auth0.com/
segmentme:
  application:
    web-client:
      configuration:
        access-control-service:
          connection:
            connectTimeOut: 20000  #milisecond
            readTimeOut: 10000  #milisecond
            writeTimeOut: 10000 #milisecond
          host: ${ACCESS_SERVICE_HOST:http://localhost:8085}
        measurement-service:
          connection:
            connectTimeOut: 20000  #milisecond
            readTimeOut: 10000  #milisecond
            writeTimeOut: 10000 #milisecond
          host: ${MEASUREMENT_SERVICE_HOST:http://localhost:8083}
    analysis:
      pool:
        corePoolSize: ${ANALYSIS_CORE_POOL_SIZE:10}
        maxPoolSize: ${ANALYSIS_MAX_POOL_SIZE:10}
        queueSize: ${ANALYSIS_QUEUE_POOL_SIZE:50}
        threadNamePrefix: ${ANALYSIS_THREAD_NAME_PREFIX:'analysis-executor-'}
    async:
      pool:
        corePoolSize: ${ASYNC_CORE_POOL_SIZE:10}
        maxPoolSize: ${ASYNC_MAX_POOL_SIZE:10}
        queueSize: ${ASYNC_QUEUE_POOL_SIZE:50}
        threadNamePrefix: ${ASYNC_THREAD_NAME_PREFIX:'async-executor-'}
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      connectionTimeout: ${REDIS_CONNECTION_TIMEOUT:25}
      readTimeOut: ${REDIS_READ_TIMEOUT:15}
      stream:
        enabled: true
        eventKey: analysis-request-event
        groupName: analysis-request-event-group
        streamPollTimeout: 1000 #milliseconds
        statisticStreamKey: statistic-event
server:
  port: 8082
