dependencies {
	api group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.11.2'
	api group: 'com.fasterxml.jackson.core', name: 'jackson-annotations', version: '2.11.2'
    api 'org.springframework.boot:spring-boot-starter-data-mongodb'
    api 'org.apache.commons:commons-lang3'
    api 'org.springframework.boot:spring-boot-starter-validation'
    api group: 'commons-codec', name: 'commons-codec', version: '1.15'

    testImplementation 'de.flapdoodle.embed:de.flapdoodle.embed.mongo'
	testImplementation 'org.springframework.boot:spring-boot-starter-web'

}

task jarTests(type: Jar, dependsOn: testClasses) {
	archiveClassifier = 'tests'
	from sourceSets.test.output
}
configurations {
	tests {
		extendsFrom testImplementation
	}
}

artifacts {
	tests jarTests
}
