dependencies {
    api project(":dependencies:models:dto:core-dto")
    api 'org.apache.commons:commons-lang3'
    api 'org.springframework.boot:spring-boot-starter-webflux'
    api 'org.springframework.boot:spring-boot-starter-webflux'
    api 'org.springframework.boot:spring-boot-starter-actuator'
    api 'org.springframework.boot:spring-boot-starter-web'
    api 'org.springframework.data:spring-data-commons'

    api 'org.springframework.boot:spring-boot-starter-security'
    api 'org.springframework.security:spring-security-oauth2-resource-server'
    api 'org.springframework.security:spring-security-oauth2-jose'
    api 'org.springframework.security:spring-security-config'
    api group: 'javax.servlet', name: 'javax.servlet-api', version: '4.0.1'

    api group: 'org.springframework.security.oauth', name: 'spring-security-oauth2', version: '2.5.0.RELEASE'
    api group: 'javax.validation', name: 'validation-api', version: '2.0.1.Final'
    api group: 'org.springframework.security', name: 'spring-security-oauth2-client', version: '5.4.2'

}

task jarTests(type: Jar, dependsOn: testClasses) {
    archiveClassifier = 'tests'
    from sourceSets.test.output
}
configurations {
    tests {
        extendsFrom testImplementation
    }
}

artifacts {
    tests jarTests
}